import { NextResponse } from "next/server";

/**
 * Markdown-for-agents content negotiation.
 * When Accept prefers text/markdown, rewrite to static Markdown mirrors
 * generated by scripts/build-agent-content.js under /agents/*.
 */
function wantsMarkdown(acceptHeader) {
  if (!acceptHeader) return false;

  const parts = acceptHeader.split(",").map((part) => {
    const [type, ...params] = part.trim().split(";");
    const qParam = params.find((p) => p.trim().startsWith("q="));
    const q = qParam ? Number.parseFloat(qParam.split("=")[1]) : 1;
    return { type: type.trim().toLowerCase(), q: Number.isFinite(q) ? q : 1 };
  });

  const markdown = parts.find((p) => p.type === "text/markdown" || p.type === "text/x-markdown");
  if (!markdown) return false;

  const html = parts.find((p) => p.type === "text/html");
  if (!html) return true;

  return markdown.q >= html.q;
}

function markdownPathFor(pathname) {
  if (pathname === "/" || pathname === "") return "/agents/home.md";
  if (pathname === "/blog" || pathname === "/blog/") return "/agents/blog.md";
  if (pathname === "/extensions" || pathname === "/extensions/") return "/agents/extensions.md";

  const blogMatch = pathname.match(/^\/blog\/([^/]+)\/?$/);
  if (blogMatch) return `/agents/blog/${blogMatch[1]}.md`;

  return null;
}

export function middleware(request) {
  if (request.method !== "GET" && request.method !== "HEAD") {
    return NextResponse.next();
  }

  const accept = request.headers.get("accept") || "";
  if (!wantsMarkdown(accept)) {
    return NextResponse.next();
  }

  const target = markdownPathFor(request.nextUrl.pathname);
  if (!target) {
    return NextResponse.next();
  }

  const url = request.nextUrl.clone();
  url.pathname = target;
  const response = NextResponse.rewrite(url);
  response.headers.set("Content-Type", "text/markdown; charset=utf-8");
  response.headers.set("Vary", "Accept");
  response.headers.set("X-Markdown-Negotiated", "1");
  return response;
}

export const config = {
  matcher: ["/", "/blog", "/blog/:slug*", "/extensions"],
};
