// Auto-generated by scripts/build-blog-data.js
// Do not edit manually

export const blogPosts = [
  {
    "slug": "ola-mundo",
    "translations": {
      "en": {
        "slug": "ola-mundo",
        "title": "Hello, World!",
        "date": "2025-05-02T10:00:00.000Z",
        "lang": "en",
        "excerpt": "First blog post. Welcome to my space for ideas, learnings, and reflections on development and technology.",
        "tags": [
          "introduction",
          "nextjs"
        ],
        "cover": "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&q=80",
        "author": "Rogério Bayer",
        "content": "\nWelcome to my blog! This is the first post in a journey of sharing knowledge, experiences, and reflections on software development, interface design, and technology in general.\n\n## Why a blog?\n\nI believe writing is one of the best ways to solidify learning. Over the years working as a full-stack developer, I've accumulated many experiences that deserve to be documented and shared.\n\n## What to expect\n\nHere you'll find:\n\n- Practical tutorials on **Next.js**, **React**, **Vue.js**, and other technologies\n- Reflections on software architecture and best practices\n- Productivity tips and tools\n- Real-world project experiences\n\n## About this site\n\nThis blog is part of my personal portfolio, built with **Next.js**, **Tailwind CSS**, and managed with **DecapCMS**. Content is versioned on GitHub and automatically published via Cloudflare Pages.\n\nFeel free to explore and, if you want, get in touch via social media!\n",
        "readingTime": 1
      },
      "fr": {
        "slug": "ola-mundo",
        "title": "Bonjour, le Monde !",
        "date": "2025-05-02T10:00:00.000Z",
        "lang": "fr",
        "excerpt": "Premier article du blog. Bienvenue dans mon espace d'idées, d'apprentissages et de réflexions sur le développement et la technologie.",
        "tags": [
          "introduction",
          "nextjs"
        ],
        "cover": "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&q=80",
        "author": "Rogério Bayer",
        "content": "\nBienvenue sur mon blog ! Ceci est le premier article d'un voyage de partage de connaissances, d'expériences et de réflexions sur le développement logiciel, le design d'interfaces et la technologie en général.\n\n## Pourquoi un blog ?\n\nJe crois que l'écriture est l'un des meilleurs moyens de solidifier l'apprentissage. Au fil des années en tant que développeur full-stack, j'ai accumulé de nombreuses expériences qui méritent d'être documentées et partagées.\n\n## Quoi attendre\n\nIci vous trouverez :\n\n- Des tutoriels pratiques sur **Next.js**, **React**, **Vue.js** et d'autres technologies\n- Des réflexions sur l'architecture logicielle et les bonnes pratiques\n- Des astuces de productivité et des outils\n- Des expériences de projets réels\n\n## À propos de ce site\n\nCe blog fait partie de mon portfolio personnel, construit avec **Next.js**, **Tailwind CSS** et géré avec **DecapCMS**. Le contenu est versionné sur GitHub et publié automatiquement via Cloudflare Pages.\n\nN'hésitez pas à explorer et, si vous le souhaitez, contactez-moi via les réseaux sociaux !\n",
        "readingTime": 1
      },
      "pt": {
        "slug": "ola-mundo",
        "title": "Olá, Mundo!",
        "date": "2025-05-02T10:00:00.000Z",
        "lang": "pt",
        "excerpt": "Primeiro post do blog. Bem-vindo ao meu espaço de ideias, aprendizados e reflexões sobre desenvolvimento e tecnologia.",
        "tags": [
          "introdução",
          "nextjs"
        ],
        "cover": "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&q=80",
        "author": "Rogério Bayer",
        "content": "\nBem-vindo ao meu blog! Este é o primeiro post de uma jornada de compartilhamento de conhecimento, experiências e reflexões sobre desenvolvimento de software, design de interfaces e tecnologia em geral.\n\n## Por que um blog?\n\nAcredito que escrever é uma das melhores formas de solidificar o aprendizado. Ao longo dos anos trabalhando com desenvolvimento full-stack, acumulei muitas experiências que merecem ser documentadas e compartilhadas.\n\n## O que esperar\n\nAqui você encontrará:\n\n- Tutoriais práticos sobre **Next.js**, **React**, **Vue.js** e outras tecnologias\n- Reflexões sobre arquitetura de software e boas práticas\n- Dicas de produtividade e ferramentas\n- Experiências reais de projetos que participei\n\n## Sobre este site\n\nEste blog é parte do meu portfolio pessoal, construído com **Next.js**, **Tailwind CSS** e gerenciado com **DecapCMS**. O conteúdo é versionado no GitHub e publicado automaticamente via Cloudflare Pages.\n\nFique à vontade para explorar e, se quiser, entre em contato pelas redes sociais!\n",
        "readingTime": 1
      }
    }
  }
];
