// Auto-generated by scripts/build-cms-data.js
// Do not edit manually

export const careerData = {
  "pt": {
    "position": {
      "name": "Frontend UI/UX Designer",
      "companyCode": "rubylabs",
      "startDate": "2026-03-03",
      "framework": "next"
    },
    "skills": {
      "languages": [
        "javascript",
        "typescript",
        "html",
        "css",
        "sass"
      ],
      "frameworks": [
        "vue",
        "nuxt",
        "react",
        "react-native",
        "nest",
        "next",
        "expo",
        "nx"
      ],
      "tools": [
        "powerbi",
        "cloudflare",
        "gcp",
        "git",
        "docker",
        "tailwind",
        "vuetify",
        "mui"
      ],
      "aiHarnesses": [
        "anthropic",
        "codex",
        "opencode",
        "deepseek",
        "open-source-ai"
      ]
    },
    "history": [
      {
        "position": "Frontend UI/UX Designer",
        "companyCode": "rubylabs",
        "startDate": "03/2026",
        "endDate": null,
        "technologies": [
          "react",
          "typescript",
          "next",
          "vercel",
          "figma"
        ],
        "description": "Atuo no projeto Sagabox, uma plataforma de assinatura de livros. Projeto e desenvolvo interfaces escaláveis e de alta qualidade usando Next.js, React, TypeScript e Tailwind CSS. Crio e mantenho design systems, utilizando Figma para transformar ideias em experiências refinadas e centradas no usuário. Atuo em colaboração próxima com stakeholders para alinhar requisitos e converter estratégia de produto em soluções intuitivas, usando dados, pesquisa de UX e testes A/B para melhorar retenção e engajamento."
      },
      {
        "position": "Software Engineer",
        "companyCode": "gupy",
        "startDate": "10/2022",
        "endDate": "03/2026",
        "technologies": [
          "vue2",
          "react",
          "nx",
          "typescript",
          "nest",
          "sass",
          "jest",
          "vitest",
          "gcp",
          "vuetify",
          "mui"
        ],
        "description": "Atuo no desenvolvimento e evolução de um produto core utilizado por mais de 100 empresas, com foco em arquitetura de frontend, escalabilidade e qualidade. Trabalho com Vue.js e React, participando de reescritas com Nx e arquiteturas de microfrontends. Contribuo com o desenvolvimento de endpoints utilizando Nest.js. Também contribuo para Design Systems, migração Vue 2 → Vue 3, decisões arquiteturais e melhorias contínuas com foco em performance, observabilidade e sustentabilidade técnica."
      },
      {
        "position": "Desenvolvedor Full-stack",
        "companyCode": "ticto",
        "startDate": "10/2021",
        "endDate": "10/2022",
        "technologies": [
          "vue2",
          "javascript",
          "php",
          "node",
          "mysql"
        ],
        "description": "Contribuí para o desenvolvimento e manutenção de plataformas internas, atuando em áreas de membros, checkouts, painéis administrativos e APIs. Também apoiei o desenvolvimento e arquitetura de APIs de rastreamento de pixels, otimizando a coleta e análise de dados."
      },
      {
        "position": "Desenvolvedor Front-end",
        "companyCode": "clientar",
        "startDate": "02/2021",
        "endDate": "10/2021",
        "technologies": [
          "vue2",
          "javascript",
          "jest",
          "cypress"
        ],
        "description": "Responsável pelo desenvolvimento front-end de um sistema CRM. Realizei a arquitetura e implementação de novas funcionalidades, incorporando testes automatizados com Jest e Cypress para testes end-to-end."
      },
      {
        "position": "Desenvolvedor Front-end e Mobile",
        "companyCode": "ecomp",
        "startDate": "08/2019",
        "endDate": "05/2022",
        "technologies": [
          "vue2",
          "react-native",
          "javascript",
          "typescript",
          "vuetify",
          "figma"
        ],
        "description": "Integrei a Empresa Júnior de Informática da UFPR, contribuindo para projetos externos de desenvolvimento front-end e mobile. Participei ativamente de Hackathons e de capacitações internas."
      }
    ]
  },
  "en": {
    "position": {
      "name": "Frontend UI/UX Designer",
      "companyCode": "rubylabs",
      "startDate": "2026-03-03",
      "framework": "next"
    },
    "skills": {
      "languages": [
        "javascript",
        "typescript",
        "html",
        "css",
        "sass"
      ],
      "frameworks": [
        "vue",
        "nuxt",
        "react",
        "react-native",
        "nest",
        "next",
        "expo",
        "nx"
      ],
      "tools": [
        "powerbi",
        "cloudflare",
        "gcp",
        "git",
        "docker",
        "tailwind",
        "vuetify",
        "mui"
      ],
      "aiHarnesses": [
        "anthropic",
        "codex",
        "opencode",
        "deepseek",
        "open-source-ai"
      ]
    },
    "history": [
      {
        "position": "Frontend UI/UX Designer",
        "companyCode": "rubylabs",
        "startDate": "03/2026",
        "endDate": null,
        "technologies": [
          "react",
          "typescript",
          "next",
          "vercel",
          "figma"
        ],
        "description": "Working at Sagabox, a subscription-based books platform. I design and build scalable, high-quality interfaces using Next.js, React, TypeScript, and Tailwind CSS. I create and maintain design systems, leveraging Figma to translate ideas into polished, user-centered experiences. I work closely with stakeholders to align requirements, turning product strategy into intuitive solutions, while using data, UX research, and A/B testing to improve retention and engagement."
      },
      {
        "position": "Software Engineer",
        "companyCode": "gupy",
        "startDate": "10/2022",
        "endDate": "03/2026",
        "technologies": [
          "vue2",
          "react",
          "nx",
          "typescript",
          "nest",
          "sass",
          "jest",
          "vitest",
          "gcp",
          "vuetify",
          "mui"
        ],
        "description": "I work on the development and evolution of a core product used by over 100 companies, focusing on frontend architecture, scalability, and quality. I work with Vue.js and React, participating in rewrites using Nx and microfrontend architectures. I also contribute to the development of endpoints using Nest.js. I also contribute to Design Systems, Vue 2 → Vue 3 migration, architectural decisions, and continuous improvements focused on performance, observability, and technical sustainability."
      },
      {
        "position": "Full-stack Developer",
        "companyCode": "ticto",
        "startDate": "10/2021",
        "endDate": "10/2022",
        "technologies": [
          "vue2",
          "javascript",
          "php",
          "node",
          "mysql"
        ],
        "description": "Contributed to the development and maintenance of internal platforms, working on member areas, checkouts, administrative panels, and APIs. Also supported the development and architecture of pixel tracking APIs, optimizing data collection and analysis."
      },
      {
        "position": "Front-end Developer",
        "companyCode": "clientar",
        "startDate": "02/2021",
        "endDate": "10/2021",
        "technologies": [
          "vue2",
          "javascript",
          "jest",
          "cypress"
        ],
        "description": "Responsible for front-end development of a CRM system. Performed architecture and implementation of new features, incorporating automated testing with Jest and Cypress for end-to-end testing."
      },
      {
        "position": "Front-end and Mobile Developer",
        "companyCode": "ecomp",
        "startDate": "08/2019",
        "endDate": "05/2022",
        "technologies": [
          "vue2",
          "react-native",
          "javascript",
          "typescript",
          "vuetify",
          "figma"
        ],
        "description": "Joined UFPR's Computer Science Junior Enterprise, contributing to external front-end and mobile development projects. Actively participated in Hackathons and internal training sessions."
      }
    ]
  },
  "fr": {
    "position": {
      "name": "Frontend UI/UX Designer",
      "companyCode": "rubylabs",
      "startDate": "2026-03-03",
      "framework": "next"
    },
    "skills": {
      "languages": [
        "javascript",
        "typescript",
        "html",
        "css",
        "sass"
      ],
      "frameworks": [
        "vue",
        "nuxt",
        "react",
        "react-native",
        "nest",
        "next",
        "expo",
        "nx"
      ],
      "tools": [
        "powerbi",
        "cloudflare",
        "gcp",
        "git",
        "docker",
        "tailwind",
        "vuetify",
        "mui"
      ],
      "aiHarnesses": [
        "anthropic",
        "codex",
        "opencode",
        "deepseek",
        "open-source-ai"
      ]
    },
    "history": [
      {
        "position": "Frontend UI/UX Designer",
        "companyCode": "rubylabs",
        "startDate": "03/2026",
        "endDate": null,
        "technologies": [
          "react",
          "typescript",
          "next",
          "vercel",
          "figma"
        ],
        "description": "Je travaille sur Sagabox, une plateforme de livres par abonnement. Je conçois et développe des interfaces scalables et de haute qualité avec Next.js, React, TypeScript et Tailwind CSS. Je crée et maintiens des design systems, en utilisant Figma pour transformer des idées en expériences soignées et centrées sur l'utilisateur. Je collabore étroitement avec les parties prenantes pour aligner les besoins et transformer la stratégie produit en solutions intuitives, tout en m'appuyant sur les données, la recherche UX et les tests A/B pour améliorer la rétention et l'engagement."
      },
      {
        "position": "Ingénieur Logiciel",
        "companyCode": "gupy",
        "startDate": "10/2022",
        "endDate": "03/2026",
        "technologies": [
          "vue2",
          "react",
          "nx",
          "typescript",
          "nest",
          "sass",
          "jest",
          "vitest",
          "gcp",
          "vuetify",
          "mui"
        ],
        "description": "Je travaille sur le développement et l'évolution d'un produit core utilisé par plus de 100 entreprises, avec un focus sur l'architecture frontend, la scalabilité et la qualité. Je travaille avec Vue.js et React, participant aux réécritures avec Nx et aux architectures de microfrontends. Je contribue également au développement de endpoints avec Nest.js. Je contribue également aux Design Systems, à la migration Vue 2 → Vue 3, aux décisions architecturales et aux améliorations continues axées sur la performance, l'observabilité et la durabilité technique."
      },
      {
        "position": "Développeur Full-stack",
        "companyCode": "ticto",
        "startDate": "10/2021",
        "endDate": "10/2022",
        "technologies": [
          "vue2",
          "javascript",
          "php",
          "node",
          "mysql"
        ],
        "description": "J'ai contribué au développement et à la maintenance de plateformes internes, travaillant sur les espaces membres, checkouts, panneaux administratifs et APIs. J'ai aussi supporté le développement et l'architecture d'APIs de tracking de pixels, optimisant la collecte et l'analyse de données."
      },
      {
        "position": "Développeur Front-end",
        "companyCode": "clientar",
        "startDate": "02/2021",
        "endDate": "10/2021",
        "technologies": [
          "vue2",
          "javascript",
          "jest",
          "cypress"
        ],
        "description": "Responsable du développement front-end d'un système CRM. J'ai réalisé l'architecture et l'implémentation de nouvelles fonctionnalités, incorporant des tests automatisés avec Jest et Cypress pour les tests end-to-end."
      },
      {
        "position": "Développeur Front-end et Mobile",
        "companyCode": "ecomp",
        "startDate": "08/2019",
        "endDate": "05/2022",
        "technologies": [
          "vue2",
          "react-native",
          "javascript",
          "typescript",
          "vuetify",
          "figma"
        ],
        "description": "J'ai rejoint l'Entreprise Junior d'Informatique de l'UFPR, contribuant à des projets externes de développement front-end et mobile. J'ai participé activement à des Hackathons et à des formations internes."
      }
    ]
  }
};
