// Auto-generated by scripts/build-cms-data.js
// Do not edit manually

export const extensionsData = {
  "pt": {
    "extensions": [
      {
        "id": 1,
        "slug": "brasil-radios-lite",
        "name": "Brasil Radios Lite",
        "icon": "/images/extensions/brasil-radios-lite-icon.webp",
        "description": "Extensão Chrome MV3 para streaming de rádio. Arquitetura baseada em service worker, offscreen document para áudio persistente e monorepo com core compartilhado entre variantes de país.",
        "link": "https://chromewebstore.google.com/detail/brasil-radios-lite/",
        "downloads": "32",
        "releaseDate": "2026-03-06",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/brasil-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Lógica principal, state management e comunicação entre contexts"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: offscreen, alarms, storage e action popup"
            }
          ],
          "impact": [
            {
              "value": "250+",
              "label": "Rádios"
            }
          ],
          "details": "Arquitetura de extensão Chrome Manifest V3 com reprodução de áudio contínua via Offscreen Document, solução necessária porque o MV3 removeu o suporte a áudio em background pages.\n\nA estrutura é organizada como monorepo (pnpm workspaces) com um pacote core compartilhado entre variantes de país. O core contém o service worker, popup, settings, offscreen player e utilitários comuns. Cada variante (Brasil, México, USA, Canadá) aplica overrides apenas de configuração, catálogo de estações e i18n.\n\nTecnologias e patterns:\n- Offscreen Document API para áudio persistente sem background page\n- Service Worker como orquestrador de estado e comunicação entre contexts\n- Sistema de override em build time para customização por país sem duplicação de código\n- Hot reload em desenvolvimento com sincronização automática core → app\n- i18n nativa do Chrome (_locales) com fallback por idioma\n- Armazenamento local (chrome.storage) para favoritos, volume e preferências\n- Catálogo de estações em JSON com metadados e múltiplos streams por rádio\n\nO pipeline de release gera bundles individuais por país com versionamento automático e validação de workspace."
        }
      },
      {
        "id": 2,
        "slug": "mexico-radios-lite",
        "name": "Mexico Radios Lite",
        "icon": "/images/extensions/mexico-radios-lite-icon.webp",
        "description": "Variante do monorepo Radios Lite para o México. Compartilha 100% do core técnico, diferenciando apenas catálogo de 151 estações e localização.",
        "link": "https://chromewebstore.google.com/detail/mexico-radios-lite/",
        "downloads": "7",
        "releaseDate": "2026-03-11",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/mexico-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Lógica principal, state management e comunicação entre contexts"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: offscreen, alarms, storage e action popup"
            }
          ],
          "impact": [
            {
              "value": "151",
              "label": "Rádios"
            }
          ],
          "details": "Variante do monorepo Radios Lite, compartilhando o mesmo core técnico das demais extensões de rádio. A arquitetura permite que múltiplos países reutilizem o mesmo código base, aplicando apenas overrides de configuração.\n\nPara o México, o override inclui:\n- Catálogo curado de 151 estações de rádio mexicanas\n- Textos e labels em espanhol via sistema de configuração unificado\n- Comportamento de busca e filtros adaptado ao mercado local\n\nTodas as funcionalidades técnicas (player offscreen, service worker, i18n, storage) são idênticas às demais variantes, demonstrando a escalabilidade da arquitetura de monorepo com core compartilhado."
        }
      },
      {
        "id": 3,
        "slug": "usa-radios-lite",
        "name": "USA Radios Lite",
        "icon": "/images/extensions/usa-radios-lite-icon.webp",
        "description": "Variante do monorepo Radios Lite para os EUA. Arquitetura MV3 com offscreen audio, service worker e catálogo de 1300+ estações americanas.",
        "link": "https://chromewebstore.google.com/detail/usa-radios-lite/",
        "downloads": "50",
        "releaseDate": "2026-03-26",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/usa-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Lógica principal, state management e comunicação entre contexts"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: offscreen, alarms, storage e action popup"
            }
          ],
          "impact": [
            {
              "value": "1300+",
              "label": "Rádios"
            }
          ],
          "details": "Maior variante do monorepo Radios Lite, com catálogo de mais de 1300 estações de rádio dos Estados Unidos. A arquitetura técnica é idêntica às demais variantes, provando a escalabilidade do core compartilhado mesmo com volumes grandes de dados.\n\nDestaques técnicos da variante USA:\n- Catálogo com 1300+ estações organizadas por estado, cidade e gênero\n- Sistema de fallback de streams: quando uma URL falha, o player tenta automaticamente o próximo stream disponível da mesma estação\n- Classificação de estações por popularidade e confiabilidade do stream\n- Mesma infraestrutura de monorepo: core compartilhado, overrides por país, build unificado\n\nA arquitetura MV3 com Offscreen Document permite que o áudio continue tocando mesmo quando o popup está fechado, um desafio técnico comum em extensões de mídia pós-MV2."
        }
      },
      {
        "id": 4,
        "slug": "canada-radios-lite",
        "name": "Canada Radios Lite",
        "icon": "/images/extensions/canada-radios-lite-icon.webp",
        "description": "Variante do monorepo Radios Lite para o Canadá. Compartilha core técnico com 500+ estações canadenses.",
        "link": "https://chromewebstore.google.com/detail/canada-radios-lite/",
        "downloads": "9",
        "releaseDate": "2026-03-13",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/canada-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Lógica principal, state management e comunicação entre contexts"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: offscreen, alarms, storage e action popup"
            }
          ],
          "impact": [
            {
              "value": "500+",
              "label": "Rádios"
            }
          ],
          "details": "Variante canadense do monorepo Radios Lite. Demonstra como a arquitetura de core compartilhado permite lançar novos produtos rapidamente com mínimo esforço de desenvolvimento.\n\nO tempo de implementação da variante Canadá foi reduzido drasticamente em comparação com a primeira versão (Brasil), pois o trabalho se resumiu a:\n- Curadoria do catálogo de 500+ estações canadenses\n- Configuração de textos em inglês e francês (idiomas oficiais do Canadá)\n- Ajustes de timezone e comportamento regional via app-config.js\n\nToda a complexidade técnica (player offscreen, gerenciamento de estado, comunicação entre contexts, i18n framework) foi herdada do core sem modificação. Isso demonstra o valor prático da arquitetura de monorepo para produtos com múltiplas variantes de mercado."
        }
      },
      {
        "id": 5,
        "slug": "your-qr-code-generator",
        "name": "Your QR Code Generator",
        "icon": "/images/extensions/your-qr-code-generator-icon.webp",
        "description": "Extensão Chrome MV3 para geração offline de QR codes. Arquitetura 100% client-side com canvas/SVG rendering, context menus e sistema de licenciamento PRO.",
        "link": "https://chromewebstore.google.com/detail/your-qr-code-generator/",
        "downloads": "4",
        "releaseDate": "2025-12-29",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/your-qr-code-generator-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Geração de QR codes, renderização canvas/SVG e lógica PRO"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: contextMenus, storage, scripting e i18n"
            }
          ],
          "impact": [
            {
              "value": "100%",
              "label": "Offline"
            }
          ],
          "details": "Extensão Chrome Manifest V3 para geração de QR codes 100% offline. Nenhum dado é enviado a servidores — toda a geração, renderização e exportação acontecem no cliente.\n\nArquitetura técnica:\n- Algoritmo de QR code implementado em JavaScript puro, sem dependências externas\n- Renderização dual: Canvas para preview rápido e SVG para exportação vetorial escalável\n- Chrome Context Menus API: geração instantânea via clique direito em links, textos selecionados e imagens\n- Sistema de licenciamento PRO com validação local via chrome.storage\n- Correção de erros Reed-Solomon com 4 níveis configuráveis (L, M, Q, H)\n- Suporte a múltiplos modos de dados: URL, texto, e-mail, telefone, SMS, WhatsApp (Click to Chat), Wi-Fi e vCard\n- i18n nativa do Chrome com suporte a 6 idiomas\n- Histórico local com persistência em chrome.storage\n\nA arquitetura PRO utiliza detecção de features baseada em licença local, desbloqueando exportação SVG, PNG de alta resolução e QR codes com logo central sem necessidade de backend."
        }
      },
      {
        "id": 6,
        "slug": "your-system-monitor",
        "name": "Your System Monitor",
        "icon": "/images/extensions/your-system-monitor-icon.webp",
        "description": "Extensão Chrome MV3 para monitoramento de CPU e memória — mais de 1.000 downloads na Chrome Web Store. Usa APIs system.cpu e system.memory com visualização via badge dinâmico, popup e gráficos históricos.",
        "link": "https://chromewebstore.google.com/detail/your-system-monitor/",
        "downloads": "1.000+",
        "releaseDate": "2025-12-12",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/your-system-monitor-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Coleta de dados, cálculos de média/pico e renderização de gráficos"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: system.cpu, system.memory, storage, alarms, notifications e offscreen"
            }
          ],
          "impact": [
            {
              "value": "1.000+",
              "label": "Downloads"
            },
            {
              "value": "4",
              "label": "Idiomas"
            }
          ],
          "details": "Extensão Chrome Manifest V3 para monitoramento de hardware via APIs privadas do Chrome (system.cpu e system.memory). A arquitetura foi projetada para ser leve, privada e extensível.\n\nComponentes técnicos:\n- Service Worker como orquestrador de coleta: utiliza chrome.alarms para agendamento periódico de amostragem de CPU e memória\n- Badge dinâmico: atualiza em tempo real com porcentagem de uso, usando código de cores (verde/amarelo/vermelho) para indicar carga\n- Popup com informações detalhadas: uso atual, média móvel, pico histórico e especificações do processador\n- Offscreen Document para gráficos históricos: isolamento de renderização Canvas em documento separado (padrão MV3 para trabalho pesado)\n- Sistema de armazenamento local com limitação circular: mantém apenas os últimos N registros para evitar crescimento indefinido do storage\n\nFeatures PRO:\n- Gráficos históricos interativos com zoom e pan\n- Exportação para PNG (captura de gráfico) e CSV (dados brutos para análise externa)\n- Notificações inteligentes com thresholds configuráveis (50-95%) e duração mínima de disparo\n\nPrivacidade: todos os dados ficam no dispositivo. Nenhuma telemetria, analytics ou comunicação externa."
        }
      },
      {
        "id": 7,
        "slug": "focus-patrol",
        "name": "Focus Patrol",
        "icon": "/images/extensions/focus-patrol-icon.webp",
        "description": "Extensão Chrome MV3 que usa IA on-device (Gemini Nano) para classificar sites em Foco, Neutro e Distração. 100% privacy-first com processamento local.",
        "link": "https://focuspatrol.bayer.ooo/",
        "downloads": "7",
        "releaseDate": "2025-10-14",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/focus-patrol-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Classificação por IA, contador de foco e lógica de notificações"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: tabs, scripting, storage, alarms e AI (Gemini Nano)"
            }
          ],
          "impact": [
            {
              "value": "5.0 ★",
              "label": "Web Store"
            }
          ],
          "details": "Extensão Chrome Manifest V3 que utiliza IA on-device (Gemini Nano via Chrome Built-in AI API) para classificar o conteúdo das páginas web em tempo real, sem enviar dados de navegação para a nuvem.\n\nArquitetura técnica:\n- Classificação local via Prompt API do Chrome: o modelo Gemini Nano roda diretamente no navegador, classificando cada página em 'Foco', 'Neutro' ou 'Distração'\n- Service Worker como motor de análise: intercepta navegação via chrome.tabs.onUpdated, extrai conteúdo textual da página via scripting e envia para o modelo local\n- Sistema de contador em tempo real: mantém contagem de sites visitados por categoria durante a sessão, exibindo no popup\n- Motor de notificações com tolerância configurável: alertas disparam apenas quando o usuário excede seu limite personalizado de distrações\n- Gamificação com sequência de foco (Focus Streak): registra dias consecutivos de produtividade\n- Modo Silencioso: usa apenas o badge colorido do ícone da extensão, sem notificações intrusivas\n\nPrivacidade:\n- Zero dados na nuvem: toda a classificação acontece localmente via modelo Gemini Nano embutido no Chrome\n- Sem backend, sem analytics, sem tracking de terceiros\n- O conteúdo das páginas nunca sai do dispositivo\n\nA extensão demonstra o uso prático de IA generativa embarcada no navegador, um campo emergente com potencial para aplicações de produtividade e bem-estar digital."
        }
      }
    ]
  },
  "en": {
    "extensions": [
      {
        "id": 1,
        "slug": "brasil-radios-lite",
        "name": "Brasil Radios Lite",
        "icon": "/images/extensions/brasil-radios-lite-icon.webp",
        "description": "Chrome MV3 extension for radio streaming. Architecture based on service worker, offscreen document for persistent audio, and monorepo with shared core across country variants.",
        "link": "https://chromewebstore.google.com/detail/brasil-radios-lite/",
        "downloads": "32",
        "releaseDate": "2026-03-06",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/brasil-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Core logic, state management and cross-context communication"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: offscreen, alarms, storage and action popup"
            }
          ],
          "impact": [
            {
              "value": "250+",
              "label": "Stations"
            }
          ],
          "details": "Chrome Manifest V3 extension architecture with continuous audio playback via Offscreen Document, a necessary solution since MV3 removed audio support from background pages.\n\nThe structure is organized as a monorepo (pnpm workspaces) with a shared core package across country variants. The core contains the service worker, popup, settings, offscreen player and common utilities. Each variant (Brazil, Mexico, USA, Canada) applies only configuration, station catalog and i18n overrides.\n\nTechnologies and patterns:\n- Offscreen Document API for persistent audio without background page\n- Service Worker as state orchestrator and cross-context communication hub\n- Build-time override system for per-country customization without code duplication\n- Hot reload in development with automatic core → app sync\n- Native Chrome i18n (_locales) with language fallback\n- Local storage (chrome.storage) for favorites, volume and preferences\n- Station catalog in JSON with metadata and multiple streams per radio\n\nThe release pipeline generates individual bundles per country with automatic versioning and workspace validation."
        }
      },
      {
        "id": 2,
        "slug": "mexico-radios-lite",
        "name": "Mexico Radios Lite",
        "icon": "/images/extensions/mexico-radios-lite-icon.webp",
        "description": "Radios Lite monorepo variant for Mexico. Shares 100% of the technical core, differentiating only by 151-station catalog and locale.",
        "link": "https://chromewebstore.google.com/detail/mexico-radios-lite/",
        "downloads": "7",
        "releaseDate": "2026-03-11",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/mexico-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Core logic, state management and cross-context communication"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: offscreen, alarms, storage and action popup"
            }
          ],
          "impact": [
            {
              "value": "151",
              "label": "Stations"
            }
          ],
          "details": "Variant of the Radios Lite monorepo, sharing the same technical core as the other radio extensions. The architecture allows multiple countries to reuse the same base code, applying only configuration overrides.\n\nFor Mexico, the override includes:\n- Curated catalog of 151 Mexican radio stations\n- Spanish texts and labels via unified configuration system\n- Search and filter behavior adapted to the local market\n\nAll technical features (offscreen player, service worker, i18n, storage) are identical to other variants, demonstrating the scalability of the monorepo architecture with shared core."
        }
      },
      {
        "id": 3,
        "slug": "usa-radios-lite",
        "name": "USA Radios Lite",
        "icon": "/images/extensions/usa-radios-lite-icon.webp",
        "description": "Radios Lite monorepo variant for the USA. MV3 architecture with offscreen audio, service worker and catalog of 1300+ American stations.",
        "link": "https://chromewebstore.google.com/detail/usa-radios-lite/",
        "downloads": "50",
        "releaseDate": "2026-03-26",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/usa-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Core logic, state management and cross-context communication"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: offscreen, alarms, storage and action popup"
            }
          ],
          "impact": [
            {
              "value": "1300+",
              "label": "Stations"
            }
          ],
          "details": "Largest variant of the Radios Lite monorepo, with a catalog of over 1300 radio stations from the United States. The technical architecture is identical to other variants, proving the scalability of the shared core even with large data volumes.\n\nTechnical highlights of the USA variant:\n- Catalog with 1300+ stations organized by state, city and genre\n- Stream fallback system: when a URL fails, the player automatically tries the next available stream from the same station\n- Station ranking by popularity and stream reliability\n- Same monorepo infrastructure: shared core, country overrides, unified build\n\nThe MV3 architecture with Offscreen Document allows audio to keep playing even when the popup is closed, a common technical challenge in media extensions post-MV2."
        }
      },
      {
        "id": 4,
        "slug": "canada-radios-lite",
        "name": "Canada Radios Lite",
        "icon": "/images/extensions/canada-radios-lite-icon.webp",
        "description": "Radios Lite monorepo variant for Canada. Shares technical core with 500+ Canadian stations.",
        "link": "https://chromewebstore.google.com/detail/canada-radios-lite/",
        "downloads": "9",
        "releaseDate": "2026-03-13",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/canada-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Core logic, state management and cross-context communication"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: offscreen, alarms, storage and action popup"
            }
          ],
          "impact": [
            {
              "value": "500+",
              "label": "Stations"
            }
          ],
          "details": "Canadian variant of the Radios Lite monorepo. Demonstrates how the shared core architecture allows launching new products quickly with minimal development effort.\n\nThe implementation time for the Canada variant was drastically reduced compared to the first version (Brazil), as the work was limited to:\n- Curating the catalog of 500+ Canadian stations\n- Configuring texts in English and French (Canada's official languages)\n- Regional timezone and behavior adjustments via app-config.js\n\nAll technical complexity (offscreen player, state management, cross-context communication, i18n framework) was inherited from the core without modification. This demonstrates the practical value of monorepo architecture for products with multiple market variants."
        }
      },
      {
        "id": 5,
        "slug": "your-qr-code-generator",
        "name": "Your QR Code Generator",
        "icon": "/images/extensions/your-qr-code-generator-icon.webp",
        "description": "Chrome MV3 extension for offline QR code generation. 100% client-side architecture with canvas/SVG rendering, context menus and PRO licensing system.",
        "link": "https://chromewebstore.google.com/detail/your-qr-code-generator/",
        "downloads": "4",
        "releaseDate": "2025-12-29",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/your-qr-code-generator-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "QR code generation, canvas/SVG rendering and PRO logic"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: contextMenus, storage, scripting and i18n"
            }
          ],
          "impact": [
            {
              "value": "100%",
              "label": "Offline"
            }
          ],
          "details": "Chrome Manifest V3 extension for 100% offline QR code generation. No data is sent to servers — all generation, rendering and export happens client-side.\n\nTechnical architecture:\n- QR code algorithm implemented in pure JavaScript, without external dependencies\n- Dual rendering: Canvas for fast preview and SVG for scalable vector export\n- Chrome Context Menus API: instant generation via right-click on links, selected text and images\n- PRO licensing system with local validation via chrome.storage\n- Reed-Solomon error correction with 4 configurable levels (L, M, Q, H)\n- Support for multiple data modes: URL, text, email, phone, SMS, WhatsApp (Click to Chat), Wi-Fi and vCard\n- Native Chrome i18n with support for 6 languages\n- Local history with persistence in chrome.storage\n\nThe PRO architecture uses local license-based feature detection, unlocking SVG export, high-resolution PNG and QR codes with centered logo without requiring a backend."
        }
      },
      {
        "id": 6,
        "slug": "your-system-monitor",
        "name": "Your System Monitor",
        "icon": "/images/extensions/your-system-monitor-icon.webp",
        "description": "Chrome MV3 extension for CPU and memory monitoring — over 1,000 downloads on the Chrome Web Store. Uses system.cpu and system.memory APIs with visualization via dynamic badge, popup and historical graphs.",
        "link": "https://chromewebstore.google.com/detail/your-system-monitor/",
        "downloads": "1.000+",
        "releaseDate": "2025-12-12",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/your-system-monitor-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Data collection, average/peak calculations and graph rendering"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: system.cpu, system.memory, storage, alarms, notifications and offscreen"
            }
          ],
          "impact": [
            {
              "value": "1.000+",
              "label": "Downloads"
            },
            {
              "value": "4",
              "label": "Languages"
            }
          ],
          "details": "Chrome Manifest V3 extension for hardware monitoring via Chrome's private APIs (system.cpu and system.memory). The architecture was designed to be lightweight, private and extensible.\n\nTechnical components:\n- Service Worker as collection orchestrator: uses chrome.alarms for periodic sampling scheduling of CPU and memory\n- Dynamic badge: updates in real-time with usage percentage, using color codes (green/yellow/red) to indicate load\n- Popup with detailed information: current usage, moving average, historical peak and processor specifications\n- Offscreen Document for historical graphs: Canvas rendering isolation in separate document (MV3 pattern for heavy work)\n- Local storage system with circular limitation: keeps only the last N records to prevent indefinite storage growth\n\nPRO features:\n- Interactive historical graphs with zoom and pan\n- Export to PNG (graph capture) and CSV (raw data for external analysis)\n- Smart notifications with configurable thresholds (50-95%) and minimum trigger duration\n\nPrivacy: all data stays on the device. No telemetry, analytics or external communication."
        }
      },
      {
        "id": 7,
        "slug": "focus-patrol",
        "name": "Focus Patrol",
        "icon": "/images/extensions/focus-patrol-icon.webp",
        "description": "Chrome MV3 extension that uses on-device AI (Gemini Nano) to classify sites as Focus, Neutral and Distraction. 100% privacy-first with local processing.",
        "link": "https://focuspatrol.bayer.ooo/",
        "downloads": "7",
        "releaseDate": "2025-10-14",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/focus-patrol-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "AI classification, focus counter and notification logic"
            },
            {
              "code": "chrome",
              "role": "MV3 APIs: tabs, scripting, storage, alarms and AI (Gemini Nano)"
            }
          ],
          "impact": [
            {
              "value": "5.0 ★",
              "label": "Web Store"
            }
          ],
          "details": "Chrome Manifest V3 extension that uses on-device AI (Gemini Nano via Chrome Built-in AI API) to classify web page content in real-time, without sending browsing data to the cloud.\n\nTechnical architecture:\n- Local classification via Chrome Prompt API: the Gemini Nano model runs directly in the browser, classifying each page as 'Focus', 'Neutral' or 'Distraction'\n- Service Worker as analysis engine: intercepts navigation via chrome.tabs.onUpdated, extracts textual page content via scripting and sends it to the local model\n- Real-time counter system: keeps count of sites visited by category during the session, displayed in the popup\n- Notification engine with configurable tolerance: alerts only trigger when the user exceeds their personalized distraction limit\n- Gamification with Focus Streak: records consecutive productive days\n- Quiet Mode: uses only the colored badge of the extension icon, without intrusive notifications\n\nPrivacy:\n- Zero data in the cloud: all classification happens locally via the Gemini Nano model embedded in Chrome\n- No backend, no analytics, no third-party tracking\n- Page content never leaves the device\n\nThe extension demonstrates the practical use of generative AI embedded in the browser, an emerging field with potential for productivity and digital well-being applications."
        }
      }
    ]
  },
  "fr": {
    "extensions": [
      {
        "id": 1,
        "slug": "brasil-radios-lite",
        "name": "Brasil Radios Lite",
        "icon": "/images/extensions/brasil-radios-lite-icon.webp",
        "description": "Extension Chrome MV3 pour le streaming radio. Architecture basée sur service worker, document offscreen pour audio persistant, et monorepo avec core partagé entre variantes par pays.",
        "link": "https://chromewebstore.google.com/detail/brasil-radios-lite/",
        "downloads": "32",
        "releaseDate": "2026-03-06",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/brasil-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Logique principale, state management et communication entre contexts"
            },
            {
              "code": "chrome",
              "role": "APIs MV3 : offscreen, alarms, storage et action popup"
            }
          ],
          "impact": [
            {
              "value": "250+",
              "label": "Stations"
            }
          ],
          "details": "Architecture d'extension Chrome Manifest V3 avec lecture audio continue via Offscreen Document, une solution nécessaire car le MV3 a supprimé le support audio des background pages.\n\nLa structure est organisée en monorepo (pnpm workspaces) avec un package core partagé entre variantes par pays. Le core contient le service worker, popup, settings, offscreen player et utilitaires communs. Chaque variante (Brésil, Mexique, USA, Canada) applique uniquement des overrides de configuration, catalogue de stations et i18n.\n\nTechnologies et patterns :\n- Offscreen Document API pour audio persistant sans background page\n- Service Worker comme orchestrateur d'état et hub de communication entre contexts\n- Système d'override au build time pour customisation par pays sans duplication de code\n- Hot reload en développement avec sync automatique core → app\n- i18n native Chrome (_locales) avec fallback par langue\n- Stockage local (chrome.storage) pour favoris, volume et préférences\n- Catalogue de stations en JSON avec métadonnées et multiples streams par radio\n\nLe pipeline de release génère des bundles individuels par pays avec versionnement automatique et validation de workspace."
        }
      },
      {
        "id": 2,
        "slug": "mexico-radios-lite",
        "name": "Mexico Radios Lite",
        "icon": "/images/extensions/mexico-radios-lite-icon.webp",
        "description": "Variante du monorepo Radios Lite pour le Mexique. Partage 100% du core technique, se différenciant uniquement par le catalogue de 151 stations et la locale.",
        "link": "https://chromewebstore.google.com/detail/mexico-radios-lite/",
        "downloads": "7",
        "releaseDate": "2026-03-11",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/mexico-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Logique principale, state management et communication entre contexts"
            },
            {
              "code": "chrome",
              "role": "APIs MV3 : offscreen, alarms, storage et action popup"
            }
          ],
          "impact": [
            {
              "value": "151",
              "label": "Stations"
            }
          ],
          "details": "Variante du monorepo Radios Lite, partageant le même core technique que les autres extensions radio. L'architecture permet à plusieurs pays de réutiliser le même code de base, appliquant uniquement des overrides de configuration.\n\nPour le Mexique, l'override inclut :\n- Catalogue curé de 151 stations de radio mexicaines\n- Textes et labels en espagnol via système de configuration unifié\n- Comportement de recherche et filtres adaptés au marché local\n\nToutes les fonctionnalités techniques (player offscreen, service worker, i18n, storage) sont identiques aux autres variantes, démontrant l'évolutivité de l'architecture monorepo avec core partagé."
        }
      },
      {
        "id": 3,
        "slug": "usa-radios-lite",
        "name": "USA Radios Lite",
        "icon": "/images/extensions/usa-radios-lite-icon.webp",
        "description": "Variante du monorepo Radios Lite pour les USA. Architecture MV3 avec audio offscreen, service worker et catalogue de 1300+ stations américaines.",
        "link": "https://chromewebstore.google.com/detail/usa-radios-lite/",
        "downloads": "50",
        "releaseDate": "2026-03-26",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/usa-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Logique principale, state management et communication entre contexts"
            },
            {
              "code": "chrome",
              "role": "APIs MV3 : offscreen, alarms, storage et action popup"
            }
          ],
          "impact": [
            {
              "value": "1300+",
              "label": "Stations"
            }
          ],
          "details": "Plus grande variante du monorepo Radios Lite, avec un catalogue de plus de 1300 stations de radio des États-Unis. L'architecture technique est identique aux autres variantes, prouvant l'évolutivité du core partagé même avec de grands volumes de données.\n\nPoints forts techniques de la variante USA :\n- Catalogue avec 1300+ stations organisées par état, ville et genre\n- Système de fallback de streams : quand une URL échoue, le player essaie automatiquement le prochain stream disponible de la même station\n- Classement des stations par popularité et fiabilité du stream\n- Même infrastructure monorepo : core partagé, overrides par pays, build unifié\n\nL'architecture MV3 avec Offscreen Document permet à l'audio de continuer à jouer même quand le popup est fermé, un défi technique commun dans les extensions média post-MV2."
        }
      },
      {
        "id": 4,
        "slug": "canada-radios-lite",
        "name": "Canada Radios Lite",
        "icon": "/images/extensions/canada-radios-lite-icon.webp",
        "description": "Variante du monorepo Radios Lite pour le Canada. Partage le core technique avec 500+ stations canadiennes.",
        "link": "https://chromewebstore.google.com/detail/canada-radios-lite/",
        "downloads": "9",
        "releaseDate": "2026-03-13",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/canada-radios-lite-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Logique principale, state management et communication entre contexts"
            },
            {
              "code": "chrome",
              "role": "APIs MV3 : offscreen, alarms, storage et action popup"
            }
          ],
          "impact": [
            {
              "value": "500+",
              "label": "Stations"
            }
          ],
          "details": "Variante canadienne du monorepo Radios Lite. Démonstre comment l'architecture de core partagé permet de lancer rapidement de nouveaux produits avec un minimum d'effort de développement.\n\nLe temps d'implémentation de la variante Canada a été drastiquement réduit par rapport à la première version (Brésil), car le travail s'est limité à :\n- Curation du catalogue de 500+ stations canadiennes\n- Configuration des textes en anglais et français (langues officielles du Canada)\n- Ajustements de timezone et comportement régional via app-config.js\n\nToute la complexité technique (player offscreen, gestion d'état, communication entre contexts, framework i18n) a été héritée du core sans modification. Cela démontre la valeur pratique de l'architecture monorepo pour les produits avec multiples variantes de marché."
        }
      },
      {
        "id": 5,
        "slug": "your-qr-code-generator",
        "name": "Your QR Code Generator",
        "icon": "/images/extensions/your-qr-code-generator-icon.webp",
        "description": "Extension Chrome MV3 pour génération hors ligne de QR codes. Architecture 100% client-side avec rendu canvas/SVG, menus contextuels et système de licence PRO.",
        "link": "https://chromewebstore.google.com/detail/your-qr-code-generator/",
        "downloads": "4",
        "releaseDate": "2025-12-29",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/your-qr-code-generator-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Génération de QR codes, rendu canvas/SVG et logique PRO"
            },
            {
              "code": "chrome",
              "role": "APIs MV3 : contextMenus, storage, scripting et i18n"
            }
          ],
          "impact": [
            {
              "value": "100%",
              "label": "Hors ligne"
            }
          ],
          "details": "Extension Chrome Manifest V3 pour génération de QR codes 100% hors ligne. Aucune donnée n'est envoyée à des serveurs — toute la génération, le rendu et l'exportation se font côté client.\n\nArchitecture technique :\n- Algorithme de QR code implémenté en JavaScript pur, sans dépendances externes\n- Rendu dual : Canvas pour preview rapide et SVG pour exportation vectorielle scalable\n- Chrome Context Menus API : génération instantanée via clic droit sur liens, textes sélectionnés et images\n- Système de licence PRO avec validation locale via chrome.storage\n- Correction d'erreurs Reed-Solomon avec 4 niveaux configurables (L, M, Q, H)\n- Support de multiples modes de données : URL, texte, e-mail, téléphone, SMS, WhatsApp (Click to Chat), Wi-Fi et vCard\n- i18n native Chrome avec support de 6 langues\n- Historique local avec persistance dans chrome.storage\n\nL'architecture PRO utilise une détection de features basée sur licence locale, débloquant l'exportation SVG, PNG haute résolution et QR codes avec logo centré sans nécessiter de backend."
        }
      },
      {
        "id": 6,
        "slug": "your-system-monitor",
        "name": "Your System Monitor",
        "icon": "/images/extensions/your-system-monitor-icon.webp",
        "description": "Extension Chrome MV3 pour surveillance du CPU et de la mémoire — plus de 1.000 téléchargements sur le Chrome Web Store. Utilise les APIs system.cpu et system.memory avec visualisation via badge dynamique, popup et graphiques historiques.",
        "link": "https://chromewebstore.google.com/detail/your-system-monitor/",
        "downloads": "1.000+",
        "releaseDate": "2025-12-12",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/your-system-monitor-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Collecte de données, calculs moyenne/pic et rendu de graphiques"
            },
            {
              "code": "chrome",
              "role": "APIs MV3 : system.cpu, system.memory, storage, alarms, notifications et offscreen"
            }
          ],
          "impact": [
            {
              "value": "1.000+",
              "label": "Téléchargements"
            },
            {
              "value": "4",
              "label": "Langues"
            }
          ],
          "details": "Extension Chrome Manifest V3 pour surveillance matérielle via les APIs privées de Chrome (system.cpu et system.memory). L'architecture a été conçue pour être légère, privée et extensible.\n\nComposants techniques :\n- Service Worker comme orchestrateur de collecte : utilise chrome.alarms pour planification d'échantillonnage périodique du CPU et de la mémoire\n- Badge dynamique : met à jour en temps réel avec le pourcentage d'utilisation, utilisant des codes couleur (vert/jaune/rouge) pour indiquer la charge\n- Popup avec informations détaillées : utilisation actuelle, moyenne mobile, pic historique et spécifications du processeur\n- Offscreen Document pour graphiques historiques : isolation de rendu Canvas dans document séparé (pattern MV3 pour travail lourd)\n- Système de stockage local avec limitation circulaire : conserve uniquement les N derniers enregistrements pour éviter la croissance indéfinie du storage\n\nFonctionnalités PRO :\n- Graphiques historiques interactifs avec zoom et pan\n- Exportation vers PNG (capture de graphique) et CSV (données brutes pour analyse externe)\n- Notifications intelligentes avec seuils configurables (50-95%) et durée minimale de déclenchement\n\nConfidentialité : toutes les données restent sur l'appareil. Pas de télémétrie, analytics ou communication externe."
        }
      },
      {
        "id": 7,
        "slug": "focus-patrol",
        "name": "Focus Patrol",
        "icon": "/images/extensions/focus-patrol-icon.webp",
        "description": "Extension Chrome MV3 utilisant l'IA embarquée (Gemini Nano) pour classer les sites en Concentration, Neutre et Distraction. 100% privacy-first avec traitement local.",
        "link": "https://focuspatrol.bayer.ooo/",
        "downloads": "7",
        "releaseDate": "2025-10-14",
        "frameworks": [
          "javascript",
          "chrome"
        ],
        "modal": {
          "images": [
            "/images/extensions/focus-patrol-1.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Classification IA, compteur de concentration et logique de notifications"
            },
            {
              "code": "chrome",
              "role": "APIs MV3 : tabs, scripting, storage, alarms et IA (Gemini Nano)"
            }
          ],
          "impact": [
            {
              "value": "5.0 ★",
              "label": "Web Store"
            }
          ],
          "details": "Extension Chrome Manifest V3 utilisant l'IA embarquée (Gemini Nano via Chrome Built-in AI API) pour classifier le contenu des pages web en temps réel, sans envoyer de données de navigation vers le cloud.\n\nArchitecture technique :\n- Classification locale via Prompt API de Chrome : le modèle Gemini Nano s'exécute directement dans le navigateur, classifiant chaque page en 'Concentration', 'Neutre' ou 'Distraction'\n- Service Worker comme moteur d'analyse : intercepte la navigation via chrome.tabs.onUpdated, extrait le contenu textuel de la page via scripting et l'envoie au modèle local\n- Système de compteur en temps réel : maintient le compte des sites visités par catégorie pendant la session, affiché dans le popup\n- Moteur de notifications avec tolérance configurable : les alertes ne se déclenchent que quand l'utilisateur dépasse sa limite personnalisée de distractions\n- Gamification avec Série de Concentration : enregistre les jours productifs consécutifs\n- Mode Silencieux : utilise uniquement le badge coloré de l'icône de l'extension, sans notifications intrusives\n\nConfidentialité :\n- Zéro donnée dans le cloud : toute la classification se fait localement via le modèle Gemini Nano intégré à Chrome\n- Pas de backend, pas d'analytics, pas de tracking tiers\n- Le contenu des pages ne quitte jamais l'appareil\n\nL'extension démontre l'utilisation pratique de l'IA générative embarquée dans le navigateur, un domaine émergent avec potentiel pour les applications de productivité et de bien-être digital."
        }
      }
    ]
  }
};
