// Auto-generated by scripts/build-cms-data.js
// Do not edit manually

export const projectsData = {
  "pt": {
    "projects": [
      {
        "id": 1,
        "slug": "powerbi",
        "name": "Dashboard Analítico de Obras",
        "image": "/images/projects/powerbi-project.png",
        "frameworks": [
          "powerbi"
        ],
        "description": "Desenvolvi dashboards analíticos para uma empresa de saneamento básico, focados no controle eficiente de obras e na otimização de processos operacionais, proporcionando maior visibilidade dos indicadores e apoio estratégico à tomada de decisões.",
        "link": null,
        "modal": {
          "images": [
            "/images/projects/powerbi-project.png"
          ],
          "technologies": [
            {
              "code": "powerbi",
              "role": "Visualização e dashboards interativos"
            }
          ],
          "impact": []
        }
      },
      {
        "id": 2,
        "slug": "farmaalg",
        "name": "App Gamificado de Exercícios de Programação",
        "image": "/images/projects/farmaalg-project.png",
        "frameworks": [
          "react-native",
          "expo",
          "springboot"
        ],
        "description": "Desenvolvimento e modernização de uma plataforma educacional que permite a resolução de exercícios de programação online. O projeto incluiu a criação de aplicativos mobile e a atualização da versão web, incorporando gamificação (pontos, medalhas e rankings) para engajar estudantes e professores.",
        "link": null,
        "modal": {
          "images": [
            "/images/projects/farmaalg-project.png"
          ],
          "technologies": [
            {
              "code": "react-native",
              "role": "App mobile multiplataforma"
            },
            {
              "code": "expo",
              "role": "Build e deploy simplificado"
            },
            {
              "code": "springboot",
              "role": "API backend robusta"
            }
          ],
          "impact": []
        }
      },
      {
        "id": 3,
        "slug": "focuspatrol",
        "name": "Focus Patrol: Extensão de Foco e Produtividade",
        "image": "/images/projects/focus-patrol-project.png",
        "frameworks": [
          "javascript",
          "cloudflare",
          "chrome"
        ],
        "description": "Utiliza IA On-Device para classificar o conteúdo das páginas. O recurso central é o Contador de Foco em Tempo Real, que exibe a quantidade de sites acessados nas categorias Foco, Neutro e Distração. O sistema de Notificações é acionado de acordo com a tolerância de distrações e o tempo escolhido. É 100% privacy-first, processando todos os dados de navegação localmente.",
        "link": "https://focuspatrol.bayer.ooo/",
        "modal": {
          "images": [
            "/images/projects/focus-patrol-project.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Lógica principal da extensão"
            },
            {
              "code": "cloudflare",
              "role": "Landing page e analytics"
            },
            {
              "code": "chrome",
              "role": "APIs de extensão do navegador"
            }
          ],
          "impact": [
            {
              "value": "5.0 ★",
              "label": "Web Store"
            },
            {
              "value": "#20",
              "label": "Product Hunt"
            },
            {
              "value": "+15",
              "label": "Países"
            }
          ]
        }
      },
      {
        "id": 4,
        "slug": "combustivel-na-rota",
        "name": "Combustível na Rota",
        "image": "/images/projects/combustivel-na-rota-project.png",
        "frameworks": [
          "react",
          "typescript",
          "tailwind",
          "cloudflare"
        ],
        "description": "Aplicação web para encontrar os melhores preços de combustível ao longo de uma rota ou nas proximidades de um local. Integra dados públicos dos programas de Nota Fiscal do Paraná (PR) e de Pernambuco (PE) com geocodificação via OpenStreetMap e roteamento via OSRM.",
        "link": "https://combustivel.bayer.ooo",
        "modal": {
          "images": [
            "/images/projects/combustivel-na-rota-project.png"
          ],
          "technologies": [
            {
              "code": "react",
              "role": "Interface e gerenciamento de estado com React 19 + Vite 6"
            },
            {
              "code": "typescript",
              "role": "Tipagem estática e segurança de código"
            },
            {
              "code": "tailwind",
              "role": "Estilização com Tailwind CSS + DaisyUI"
            },
            {
              "code": "cloudflare",
              "role": "Deploy frontend + proxy de APIs via Cloudflare Workers"
            }
          ],
          "impact": [
            {
              "value": "PR + PE",
              "label": "Estados cobertos"
            },
            {
              "value": "20 km",
              "label": "Raio de busca"
            }
          ]
        }
      }
    ]
  },
  "en": {
    "projects": [
      {
        "id": 1,
        "slug": "powerbi",
        "name": "Construction Analytics Dashboard",
        "image": "/images/projects/powerbi-project.png",
        "frameworks": [
          "powerbi"
        ],
        "description": "Developed analytical dashboards for a basic sanitation company, focused on efficient construction control and operational process optimization, providing greater visibility of indicators and strategic support for decision-making.",
        "link": null,
        "modal": {
          "images": [
            "/images/projects/powerbi-project.png"
          ],
          "technologies": [
            {
              "code": "powerbi",
              "role": "Visualization and interactive dashboards"
            }
          ],
          "impact": []
        }
      },
      {
        "id": 2,
        "slug": "farmaalg",
        "name": "Gamified Programming Exercises App",
        "image": "/images/projects/farmaalg-project.png",
        "frameworks": [
          "react-native",
          "expo",
          "springboot"
        ],
        "description": "Development and modernization of an educational platform that allows online programming exercise solving. The project included creating mobile applications and updating the web version, incorporating gamification (points, badges, and rankings) to engage students and teachers.",
        "link": null,
        "modal": {
          "images": [
            "/images/projects/farmaalg-project.png"
          ],
          "technologies": [
            {
              "code": "react-native",
              "role": "Cross-platform mobile app"
            },
            {
              "code": "expo",
              "role": "Simplified build and deploy"
            },
            {
              "code": "springboot",
              "role": "Robust backend API"
            }
          ],
          "impact": []
        }
      },
      {
        "id": 3,
        "slug": "focuspatrol",
        "name": "Focus Patrol: Privacy-First Focus & Productivity Extension",
        "image": "/images/projects/focus-patrol-project.png",
        "frameworks": [
          "javascript",
          "cloudflare",
          "chrome"
        ],
        "description": "Utilizing On-Device AI to classify page content. Its core feature is the Real-Time Focus Counter, which displays the number of sites accessed in the Focus, Neutral, and Distraction categories. A Notifications system is triggered according to the distraction tolerance and the chosen time. It is 100% privacy-first, processing all browsing data locally.",
        "link": "https://focuspatrol.bayer.ooo/",
        "modal": {
          "images": [
            "/images/projects/focus-patrol-project.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Core extension logic"
            },
            {
              "code": "cloudflare",
              "role": "Landing page and analytics"
            },
            {
              "code": "chrome",
              "role": "Browser extension APIs"
            }
          ],
          "impact": [
            {
              "value": "5.0 ★",
              "label": "Web Store"
            },
            {
              "value": "#20",
              "label": "Product Hunt"
            },
            {
              "value": "+15",
              "label": "Countries"
            }
          ]
        }
      },
      {
        "id": 4,
        "slug": "combustivel-na-rota",
        "name": "Fuel on Route",
        "image": "/images/projects/combustivel-na-rota-project.png",
        "frameworks": [
          "react",
          "typescript",
          "tailwind",
          "cloudflare"
        ],
        "description": "Web application to find the best fuel prices along a route or near a location. Integrates public data from Paraná (PR) and Pernambuco (PE) fiscal note programs with geocoding via OpenStreetMap and routing via OSRM.",
        "link": "https://combustivel.bayer.ooo",
        "modal": {
          "images": [
            "/images/projects/combustivel-na-rota-project.png"
          ],
          "technologies": [
            {
              "code": "react",
              "role": "UI and state management with React 19 + Vite 6"
            },
            {
              "code": "typescript",
              "role": "Static typing and code safety"
            },
            {
              "code": "tailwind",
              "role": "Styling with Tailwind CSS + DaisyUI"
            },
            {
              "code": "cloudflare",
              "role": "Frontend deploy + API proxy via Cloudflare Workers"
            }
          ],
          "impact": [
            {
              "value": "PR + PE",
              "label": "States covered"
            },
            {
              "value": "20 km",
              "label": "Search radius"
            }
          ]
        }
      }
    ]
  },
  "fr": {
    "projects": [
      {
        "id": 1,
        "slug": "powerbi",
        "name": "Tableau de Bord Analytique de Construction",
        "image": "/images/projects/powerbi-project.png",
        "frameworks": [
          "powerbi"
        ],
        "description": "J'ai développé des tableaux de bord analytiques pour une entreprise d'assainissement, axés sur le contrôle efficace des constructions et l'optimisation des processus opérationnels, offrant une plus grande visibilité des indicateurs et un soutien stratégique à la prise de décision.",
        "link": null,
        "modal": {
          "images": [
            "/images/projects/powerbi-project.png"
          ],
          "technologies": [
            {
              "code": "powerbi",
              "role": "Visualisation et tableaux de bord interactifs"
            }
          ],
          "impact": []
        }
      },
      {
        "id": 2,
        "slug": "farmaalg",
        "name": "App Gamifiée d'Exercices de Programmation",
        "image": "/images/projects/farmaalg-project.png",
        "frameworks": [
          "react-native",
          "expo",
          "springboot"
        ],
        "description": "Développement et modernisation d'une plateforme éducative permettant la résolution d'exercices de programmation en ligne. Le projet incluait la création d'applications mobiles et la mise à jour de la version web, incorporant la gamification (points, badges et classements) pour engager étudiants et professeurs.",
        "link": null,
        "modal": {
          "images": [
            "/images/projects/farmaalg-project.png"
          ],
          "technologies": [
            {
              "code": "react-native",
              "role": "App mobile multiplateforme"
            },
            {
              "code": "expo",
              "role": "Build et déploiement simplifiés"
            },
            {
              "code": "springboot",
              "role": "API backend robuste"
            }
          ],
          "impact": []
        }
      },
      {
        "id": 3,
        "slug": "focuspatrol",
        "name": "Focus Patrol : Extension de Concentration et Productivité",
        "image": "/images/projects/focus-patrol-project.png",
        "frameworks": [
          "javascript",
          "cloudflare",
          "chrome"
        ],
        "description": "Utilisant l'IA Embarquée pour classer le contenu des pages. Sa fonctionnalité centrale est le Compteur de Concentration en Temps Réel, qui affiche la quantité de sites accédés dans les catégories Concentration, Neutre et Distraction. Un système de Notifications est déclenché en fonction de la tolérance aux distractions et du temps choisi. Elle est 100% privacy-first, traitant toutes les données localement.",
        "link": "https://focuspatrol.bayer.ooo/",
        "modal": {
          "images": [
            "/images/projects/focus-patrol-project.png"
          ],
          "technologies": [
            {
              "code": "javascript",
              "role": "Logique principale de l'extension"
            },
            {
              "code": "cloudflare",
              "role": "Landing page et analytics"
            },
            {
              "code": "chrome",
              "role": "APIs d'extension du navigateur"
            }
          ],
          "impact": [
            {
              "value": "5.0 ★",
              "label": "Web Store"
            },
            {
              "value": "#20",
              "label": "Product Hunt"
            },
            {
              "value": "+15",
              "label": "Pays"
            }
          ]
        }
      },
      {
        "id": 4,
        "slug": "combustivel-na-rota",
        "name": "Carburant sur la Route",
        "image": "/images/projects/combustivel-na-rota-project.png",
        "frameworks": [
          "react",
          "typescript",
          "tailwind",
          "cloudflare"
        ],
        "description": "Application web pour trouver les meilleurs prix de carburant le long d'un itinéraire ou près d'un lieu. Intègre des données publiques des programmes de notes fiscales du Paraná (PR) et du Pernambuco (PE) avec géocodage via OpenStreetMap et routage via OSRM.",
        "link": "https://combustivel.bayer.ooo",
        "modal": {
          "images": [
            "/images/projects/combustivel-na-rota-project.png"
          ],
          "technologies": [
            {
              "code": "react",
              "role": "Interface et gestion d'état avec React 19 + Vite 6"
            },
            {
              "code": "typescript",
              "role": "Typage statique et sécurité du code"
            },
            {
              "code": "tailwind",
              "role": "Stylisation avec Tailwind CSS + DaisyUI"
            },
            {
              "code": "cloudflare",
              "role": "Déploiement frontend + proxy d'APIs via Cloudflare Workers"
            }
          ],
          "impact": [
            {
              "value": "PR + PE",
              "label": "États couverts"
            },
            {
              "value": "20 km",
              "label": "Rayon de recherche"
            }
          ]
        }
      }
    ]
  }
};
